// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu_GLfJ36MzFbOUAFsg4F1bn8zmFVLwyg',
    appId: '1:359957603706:web:9cdfb8f8b1571d56d8e2c3',
    messagingSenderId: '359957603706',
    projectId: 'demineur-fbb25',
    authDomain: 'demineur-fbb25.firebaseapp.com',
    storageBucket: 'demineur-fbb25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSN6W-7lNxGrxO9vP4Q7Ejt9O5iRTph3E',
    appId: '1:359957603706:android:321a3d013b807b62d8e2c3',
    messagingSenderId: '359957603706',
    projectId: 'demineur-fbb25',
    storageBucket: 'demineur-fbb25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmHEbOvkbbqJCvhGjJp5dH-3dvyA0wJNU',
    appId: '1:359957603706:ios:de8f8e520013428bd8e2c3',
    messagingSenderId: '359957603706',
    projectId: 'demineur-fbb25',
    storageBucket: 'demineur-fbb25.appspot.com',
    iosBundleId: 'com.example.tp02',
  );
}
